# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5f1fc3edd9b5440f9c0e1c11935bd129fb9c49acaab620a8cc85948fbc40ebdca8e599d3498142057bbe09c5b176cd26d03ecce7febbef4f1333062c600dd300

test:
  secret_key_base: c75a237ecad1c6c485d5f23587ac9e7e03473375f36bf004d898b1dbe87e811a21b03271e3fbb53d236cf6cc73f4fcbf2b87475ce79fd235188ccdcfa63d0b63

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
